# fly.toml app configuration file generated for project-fractured-god on 2025-04-25T17:22:55+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'project-fractured-god'
primary_region = 'fra'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[build]
  dockerfile = "Battle Spells.Api/Dockerfile"

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

[env]
  ASPNETCORE_ENVIRONMENT = "Development"
  ConnectionStrings__Default = "Data Source=/litefs/battle.db"